/***********************************I-DEP-JRR-AF-0-24/04/2014*****************************************/
select pxp.f_insert_testructura_gui ('PREIACT.1', 'PREIACT');
select pxp.f_insert_testructura_gui ('PREIACT.2', 'PREIACT');
select pxp.f_insert_testructura_gui ('PREIACT.3', 'PREIACT');
select pxp.f_insert_testructura_gui ('PREIACT.1.1', 'PREIACT.1');
select pxp.f_insert_testructura_gui ('PREIACT.1.2', 'PREIACT.1');
select pxp.f_insert_testructura_gui ('PREIACT.2.1', 'PREIACT.2');
select pxp.f_insert_testructura_gui ('PREIACT.2.2', 'PREIACT.2');
select pxp.f_insert_testructura_gui ('PREIACT.2.1.1', 'PREIACT.2.1');
select pxp.f_insert_tprocedimiento_gui ('WF_GATNREP_SEL', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_ALM_SEL', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_DEPFILUSU_SEL', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREING_INS', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREING_MOD', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREING_ELI', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREING_SEL', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_INGRES_GEN', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREING_REV', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CATCMB_SEL', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_DEPUSUCOMB_SEL', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_MONEDA_SEL', 'PREIACT', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'PREIACT.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'PREIACT.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'PREIACT.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'PREIACT.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'PREIACT.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPPROC_SEL', 'PREIACT.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'PREIACT.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_INS', 'PREIACT.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_MOD', 'PREIACT.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_ELI', 'PREIACT.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_SEL', 'PREIACT.1.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_ITEMNOTBASE_SEL', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_ALM_SEL', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('AF_CLAS_SEL', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_DEPUSUCOMB_SEL', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREDET_INS', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREDET_MOD', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREDET_ELI', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_PREDET_SEL', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CATCMB_SEL', 'PREIACT.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('ALM_CLA_ARB_SEL', 'PREIACT.2.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_ARB_SEL', 'PREIACT.2.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_ITMSRCHARB_SEL', 'PREIACT.2.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SAL_ITMALM_SEL', 'PREIACT.2.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_SUBSIS_SEL', 'PREIACT.2.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_PACATI_SEL', 'PREIACT.2.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CAT_INS', 'PREIACT.2.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CAT_MOD', 'PREIACT.2.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CAT_ELI', 'PREIACT.2.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CAT_SEL', 'PREIACT.2.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CATCMB_SEL', 'PREIACT.2.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('SEG_SUBSIS_SEL', 'PREIACT.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_PACATI_SEL', 'PREIACT.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CAT_INS', 'PREIACT.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CAT_MOD', 'PREIACT.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CAT_ELI', 'PREIACT.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CAT_SEL', 'PREIACT.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CATCMB_SEL', 'PREIACT.3', 'no');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'WF_DES_SEL', 'PREIACT.1.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'WF_DWF_SEL', 'PREIACT.1');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SEG_SUBSIS_SEL', 'PREIACT.3');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_PACATI_SEL', 'PREIACT.3');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CAT_SEL', 'PREIACT.3');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CATCMB_SEL', 'PREIACT.3');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CAT_INS', 'PREIACT.3');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CAT_MOD', 'PREIACT.3');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CAT_ELI', 'PREIACT.3');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SEG_SUBSIS_SEL', 'PREIACT.2.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_PACATI_SEL', 'PREIACT.2.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CAT_SEL', 'PREIACT.2.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CATCMB_SEL', 'PREIACT.2.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CAT_INS', 'PREIACT.2.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CAT_MOD', 'PREIACT.2.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CAT_ELI', 'PREIACT.2.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_ITMALM_SEL', 'PREIACT.2.1.1');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'ALM_CLA_ARB_SEL', 'PREIACT.2.1');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_ARB_SEL', 'PREIACT.2.1');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_ITMSRCHARB_SEL', 'PREIACT.2.1');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'PM_CATCMB_SEL', 'PREIACT.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_ITEMNOTBASE_SEL', 'PREIACT.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_ALM_SEL', 'PREIACT.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_PREDET_SEL', 'PREIACT.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_PREDET_INS', 'PREIACT.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_PREDET_MOD', 'PREIACT.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'SAL_PREDET_ELI', 'PREIACT.2');
select pxp.f_insert_trol_procedimiento_gui ('ADQ - Preingreso AF', 'AF_CLAS_SEL', 'PREIACT.2');

/***********************************F-DEP-JRR-AF-0-24/04/2014*****************************************/